apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tailgate-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailgate-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tailgate-operator.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
        {{- with .Values.operator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tailgate-operator.operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tailgate-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
      - name: operator
        image: {{ include "tailgate-operator.operator.image" . }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GW_IMAGE
          value: {{ include "tailgate-operator.gateway.image" . | quote }}
        - name: TS_TAILNET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tailnet.secretName }}
              key: TS_TAILNET
        - name: TS_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tailnet.secretName }}
              key: TS_OAUTH_CLIENT_ID
        - name: TS_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tailnet.secretName }}
              key: TS_OAUTH_CLIENT_SECRET
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
