{{- if .Values.tailnet.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tailnet.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailgate-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_TAILNET: {{ .Values.tailnet.tailnet | default "-" | quote }}
  TS_OAUTH_CLIENT_ID: {{ .Values.tailnet.oauthClientID | quote }}
  TS_OAUTH_CLIENT_SECRET: {{ .Values.tailnet.oauthClientSecret | quote }}
{{- end }}
