{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailgate-operator.fullname" . }}-ui
  labels:
    {{- include "tailgate-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tailgate-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end -}}
